### ISSUE TITLE
缩放级别重置按钮点击报错

### ISSUE THREAD

**Issue by loyalove** [zouyaoji/vue-cesium#24]
``javascropt
Cesium.js:559 An error occurred while rendering.  Rendering has stopped.
undefined
RangeError: Invalid array length
RangeError: Invalid array length
    at A (http://127.0.0.1:7001/cesium/Cesium.js:550:30793)
    at S.createPotentiallyVisibleSet (http://127.0.0.1:7001/cesium/Cesium.js:551:1946)
    at nt (http://127.0.0.1:7001/cesium/Cesium.js:551:25551)
    at tt (http://127.0.0.1:7001/cesium/Cesium.js:551:22934)
    at mt (http://127.0.0.1:7001/cesium/Cesium.js:552:727)
    at _t (http://127.0.0.1:7001/cesium/Cesium.js:552:914)
    at Me.render (http://127.0.0.1:7001/cesium/Cesium.js:552:13980)
    at x.render (http://127.0.0.1:7001/cesium/Cesium.js:559:27418)
    at t (http://127.0.0.1:7001/cesium/Cesium.js:559:20868)
``

**Comment by loyalove** [comment]
默认坐标有误
